services:
  - type: worker  # ← Change from 'web' to 'worker'
    name: slackbot-worker
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.slack_app  # ← Run the Socket Mode app directly
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: SLACK_APP_TOKEN  
        sync: false
      - key: SERPER_API_KEY
        sync: false